INSERT INTO author (id, name, version) VALUES (1, 'Author 1', 0);
INSERT INTO author (id, name, version) VALUES (2, 'Author 2', 0);
INSERT INTO author (id, name, version) VALUES (3, 'Author 3', 0);
INSERT INTO author (id, name, version) VALUES (4, 'Author 4', 0);
INSERT INTO author (id, name, version) VALUES (5, 'Author 5', 0);
INSERT INTO author (id, name, version) VALUES (6, 'Author 6', 0);
INSERT INTO author (id, name, version) VALUES (7, 'Author 7', 0);
INSERT INTO author (id, name, version) VALUES (8, 'Author 8', 0);
INSERT INTO author (id, name, version) VALUES (9, 'Author 9', 0);
INSERT INTO author (id, name, version) VALUES (10, 'Author 10', 0);
INSERT INTO author (id, name, version) VALUES (11, 'Author 11', 0);
INSERT INTO author (id, name, version) VALUES (12, 'Author 12', 0);
INSERT INTO author (id, name, version) VALUES (13, 'Author 13', 0);
INSERT INTO author (id, name, version) VALUES (14, 'Author 14', 0);
INSERT INTO author (id, name, version) VALUES (15, 'Author 15', 0);
INSERT INTO author (id, name, version) VALUES (16, 'Author 16', 0);
INSERT INTO author (id, name, version) VALUES (17, 'Author 17', 0);
INSERT INTO author (id, name, version) VALUES (18, 'Author 18', 0);
INSERT INTO author (id, name, version) VALUES (19, 'Author 19', 0);

INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (1, '2008-05-08', 'Effective Java', 1, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (2, '2015-10-01', 'Java Persistence with Hibernate', 2, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (3, '2014-08-28', 'Java 8 in Action', 3, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (4, '2014-03-12', 'Continuous Enterprise Development in Java', 4, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (5, '2010-09-08', 'Enterprise JavaBeans 3.1', 5, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (6, '2014-04-29', 'Java Performance The Definitive Guide', 6, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (7, '2017-04-04', 'Hibernate Tips', 7, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (8, '2017-04-04', 'Hibernate Tips', 8, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (9, '2017-04-04', 'Hibernate Tips', 9, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (10, '2017-04-04', 'Hibernate Tips', 10, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (11, '2017-04-04', 'Hibernate Tips', 11, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (12, '2017-04-04', 'Hibernate Tips', 12, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (13, '2017-04-04', 'Hibernate Tips', 13, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (14, '2017-04-04', 'Hibernate Tips', 14, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (15, '2017-04-04', 'Hibernate Tips', 15, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (16, '2017-04-04', 'Hibernate Tips', 16, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (17, '2017-04-04', 'Hibernate Tips', 17, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (18, '2017-04-04', 'Hibernate Tips', 18, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (19, '2017-04-04', 'Hibernate Tips', 19, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (20, '2017-04-04', 'Hibernate Tips', 1, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (21, '2017-04-04', 'Hibernate Tips', 1, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (22, '2017-04-04', 'Hibernate Tips', 1, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (23, '2017-04-04', 'Hibernate Tips', 1, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (24, '2017-04-04', 'Hibernate Tips', 1, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (25, '2017-04-04', 'Hibernate Tips', 1, 0);
INSERT INTO book (id, publishingdate, title, fk_author, version) VALUES (26, '2017-04-04', 'Hibernate Tips', 1, 0);
